services:
  ros2:
    build:
      context: .
    container_name: ros2_container
    volumes:
      - ./ros2_ws:/ros2_ws
    tty: true
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    network_mode: "host"
    privileged: true
    devices:
      - /dev:/dev
    # command: ["bash"]
    command: bash -c "
      terminator"
